name: Pipeline Testes Unitários

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '15 6 * * *'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test

      - name: Publicar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: mochawesome-report/